spring.application.name=Pawel-Ryfiak-Traffic-Lights-2
# Set logging level to DEBUG
logging.level.be.kdg.programming5=DEBUG

# Hibernate SQL logging - required for query optimization verification
# keeps track of the amount of queries by turning on query logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Disable Open Session in View (requires @Transactional in service layer)
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always

# Postgresql configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:postgresql://localhost:9432/programming5
spring.datasource.username=student
spring.datasource.password=Student_1234

# Internationalization configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false


